const o = (...opts) => [opts, 0];

const standard = {
  1: [
    o('Confidentiality, Integrity, Availability', 'Control, Identity, Access', 'Confidentiality, Identity, Authorisation', 'Cryptography, Integrity, Authentication'),
    o('Actions are traceable to those responsible', 'Information is never disclosed', 'Users prove their identity', 'Data is never altered'),
    o('Risk = Assets x Vulnerabilities x Threats', 'Risk = Threats - Controls', 'Risk = Assets + Vulnerabilities', 'Risk = Vulnerabilities x Cost'),
    o('A vulnerability is a weakness; a threat is a potential violation of security', 'A vulnerability is an attack in progress; a threat is a flaw', 'They are identical terms', 'A threat is a weakness; a vulnerability is the actual attack'),
    o('Deception, countered by Integrity', 'Disclosure, countered by Confidentiality', 'Disruption, countered by Availability', 'Usurpation, countered by Authentication'),
    o('When in doubt, do not grant access', 'Keep the mechanism as simple as possible', 'Never rely on obscurity', 'Always grant access unless explicitly denied'),
    o('Quantitative uses price and probability to compute expected loss; Qualitative uses ad-hoc expert advice', 'Quantitative uses expert opinion; Qualitative uses formulas', 'Both rely purely on mathematics', 'Quantitative ignores probability; Qualitative ignores cost'),
    o('Prevention, Detection, Recovery/Reaction', 'Policy, Mechanism, Audit', 'Identify, Protect, Respond', 'Design, Build, Operate'),
    o('Hardware, OS Kernel, Operating System, Services, Applications', 'Applications, Services, OS, Kernel, Hardware', 'Hardware, Firmware, Network, OS, Users', 'Kernel, Hardware, Services, OS, Applications'),
    o('Semi-technical', 'Technical', 'Non-technical', 'Administrative'),
  ],
  2: [
    o('Security, Robustness, Capacity', 'Confidentiality, Integrity, Availability', 'Identification, Authentication, Authorisation', 'Speed, Cost, Size'),
    o('Something you are (biometrics)', 'Something you know', 'Something you have', 'Something you do once'),
    o('No reads up: read allowed only if object level <= subject clearance', 'No writes down: write allowed only if object level >= subject clearance', 'No reads down: read allowed only if object level >= subject clearance', 'Read allowed only if levels are equal'),
    o('In DAC the resource owner grants rights; in MAC rights are fixed centrally by an administrator', 'In DAC an administrator grants rights; in MAC the owner does', 'Both are controlled solely by the owner', 'DAC is for files only; MAC is for users only'),
    o('The Chinese Wall model', 'The Bell-LaPadula model', 'The Biba model', 'The Reference Monitor model'),
    o('Tamper-resistance, complete mediation, easy verification', 'Confidentiality, integrity, availability', 'Identification, authentication, accountability', 'Speed, simplicity, scalability'),
    o('Poor overview of rights per object and difficult revocation', 'It cannot authenticate users', 'It exposes passwords in plaintext', 'It only works for a single user'),
    o('It verifies the TGT and issues a service ticket and session key for the application server', 'It hashes the user password into a key', 'It stores all user passwords', 'It encrypts the final application data'),
    o('Simple integrity: write allowed only if subject integrity >= object integrity (no write up)', 'Write allowed only if subject integrity <= object integrity', 'Write is always denied', 'Write allowed only if levels are equal'),
    o('Chinese Wall: permissions change with access history, blocking the competing dataset', 'Bell-LaPadula: she lacks clearance for Pizza Hut', 'Biba: Pizza Hut data has higher integrity', 'DAC: the owner revoked her access'),
  ],
  3: [
    o('A 1-bit change in plaintext or key produces large changes in the ciphertext', 'The ciphertext shrinks with each round', 'Keys avalanche into smaller subkeys', 'Plaintext statistics are preserved'),
    o('Confusion and Diffusion', 'Substitution and Addition', 'Encryption and Decryption', 'Hashing and Salting'),
    o('XOR (Exclusive OR)', 'AND', 'Modular multiplication', 'Bit rotation'),
    o('Three 56-bit keys applied Encrypt-Decrypt-Encrypt', 'One 128-bit key', 'Two 64-bit keys', 'Three 128-bit keys'),
    o('Rijndael; no, it does not use a Feistel network', 'Rijndael; yes, it uses a Feistel network', 'DES; no Feistel network', 'Blowfish; yes, Feistel based'),
    o('Infeasible to find any two distinct messages with the same hash', 'Infeasible to reverse a hash to its message', 'Infeasible to find a second message matching a given message hash', 'Infeasible to compute the hash at all'),
    o('N x (N - 1) / 2', 'N x N', '2^N', 'N - 1'),
    o('Certification Authority, Registration Authority, Subscribers, Repository/Archive', 'Sender, Receiver, Key, Cipher', 'CA, Firewall, VPN, IDS', 'Hash, Salt, Key, Certificate'),
    o('An S-box does key-controlled substitution (non-linearity); a P-box permutes bits', 'An S-box permutes bits; a P-box substitutes', 'Both only permute bits', 'Both only substitute values'),
    o("Alice's public key; it guarantees data integrity and non-repudiation", "Alice's private key; confidentiality and integrity", "Bob's public key; authentication and confidentiality", "A shared symmetric key; integrity only"),
  ],
  4: [
    o('The Local Security Authority (LSA)', 'The Security Accounts Manager (SAM)', 'Active Directory', 'The Reference Monitor'),
    o('rw-r--r--', 'rwxr--r--', 'rw-rw-r--', 'r--r--r--'),
    o('An ACL entry defining allow or deny permissions for a specific principal SID', 'A list of all users on the system', 'A Linux file permission bit', 'A password hash record'),
    o('False', 'True'),
    o('It masks out bits from the default permissions of newly created files', 'It grants root access to a user', 'It encrypts new files', 'It lists active processes'),
    o('The Discretionary Access Control List (DACL)', 'The System Access Control List (SACL)', 'The Owner SID', 'The Primary Group SID'),
    o('Real UID is inherited from the parent; effective UID may come from the parent or a SUID file owner', 'Real UID comes from SUID; effective UID from the parent', 'They are always identical', 'Effective UID is always 0'),
    o('Owner SID, DACL, SACL', 'inode, umask, SUID', 'LSA, SAM, UAC', 'TGT, TGS, AS'),
    o('Only the file owner (or root) may remove files in that directory', 'It makes the directory read-only', 'It runs files with owner privilege', 'It hides the directory'),
    o('750: owner rwx, group r-x, others none', '755: owner rwx, group r-x, others r-x', '640: owner rw-, group r--, others none', '777: full access for everyone'),
  ],
  5: [
    o("Program code executed without the user's consent that carries out harmful functionality", 'Any program that uses the network', 'Software with a graphical interface', 'A legally licensed application'),
    o('A Trojan masquerades as helpful software; a Rootkit hides processes and maintains privileged access', 'A Trojan spreads over the network; a Rootkit needs a host file', 'They are the same thing', 'A Rootkit masquerades as a game; a Trojan hides files'),
    o('Data Execution Protection, Address Space Layout Randomisation, Canaries', 'Firewalls, VPNs, IDS', 'Encryption, Hashing, Salting', 'DEP, SQL parameterisation, XSS filtering'),
    o('The return address', 'The heap pointer', 'The program counter register', 'The function name'),
    o('Cross-Site Request Forgery; it exploits an existing authenticated session', 'Cross-Site Reflected Forgery; it injects scripts', 'Client-Side Request Filtering; it blocks cookies', 'Cross-Site Resource Fetch; it steals files'),
    o('It makes the query condition always true (1=1), granting access without a valid password', 'It deletes the password table', 'It encrypts the query', 'It overflows the login buffer'),
    o('Encryption makes a document unreadable without a key; watermarking leaves it intact with a hidden marker', 'Both make the document unreadable', 'Watermarking needs a key; encryption does not', 'Encryption hides a copyright marker inside the file'),
    o('Any three of: Unobtrusive, Readily Detectable, Unambiguous, Innumerable, Robust', 'Encrypted, Compressed, Signed', 'Fast, Cheap, Small', 'Visible, Removable, Editable'),
    o('It tweaks lower-order bits and adds jitter to stop watermark bits being located, keeping the object intact', 'It floods the detector with requests', 'It encrypts the watermark', 'It overflows the media buffer'),
    o('Cross-Site Scripting (XSS); the attacker could run arbitrary JavaScript to steal session cookies', 'SQL Injection; the attacker could drop tables', 'CSRF; the attacker could forge a bank transfer', 'Buffer overflow; the attacker could overwrite the return address'),
  ],
};

const extended = {
  1: [
    o('Confidentiality, Integrity, Availability', 'Control, Identity, Access', 'Confidentiality, Identity, Authorisation', 'Cryptography, Integrity, Authentication'),
    o('Authentication and Accountability', 'Authorisation and Auditing', 'Privacy and Cost', 'Prevention and Recovery'),
    o('The methods used to fulfil policy requirements; the implementation of security', 'The rules specifying what security to achieve', 'The monetary value of an asset', 'A potential violation of security'),
    o('A vulnerability is a weakness; a threat is a potential violation of security', 'A threat is a weakness; a vulnerability is the actual attack', 'They mean the same thing', 'A vulnerability is a deliberate act; a threat is a flaw'),
    o('Monetary replacement value and lost revenue', 'Price and probability', 'Hardware cost and software cost', 'Asset count and threat count'),
    o('Risk = Assets x Vulnerabilities x Threats', 'Risk = Assets + Threats', 'Risk = Threats / Controls', 'Risk = Vulnerabilities x Cost'),
    o('Quantitative uses price and probability for expected loss; Qualitative uses ad-hoc expert advice', 'Quantitative uses expert opinion; Qualitative uses formulas', 'Both are purely mathematical', 'Quantitative ignores cost; Qualitative ignores probability'),
    o('Act of Human Error or Failure, Forces of Nature, Deviation in Quality of Services', 'Disclosure, Deception, Disruption', 'Prevention, Detection, Recovery', 'Hardware, Software, Network'),
    o('Integrity', 'Confidentiality', 'Availability', 'Authentication'),
    o('Snooping, sniffing, wiretapping', 'Spoofing and repudiation', 'Modification and delay', 'Denial of service and replay'),
    o('Prevention, Detection, Recovery/Reaction', 'Policy, Mechanism, Audit', 'Confidentiality, Integrity, Availability', 'Identify, Protect, Respond'),
    o('SSL encryption or credit card validation', 'Burglar alarms and locks', 'Firewalls and IDS', 'Vulnerability scanning'),
    o('When in doubt, do not grant access', 'No security by obscurity', 'Keep the mechanism simple', 'Grant access unless explicitly denied'),
    o('No security by obscurity', 'When in doubt, deny access', 'Use minimum necessary privileges', 'Keep designs hidden from attackers'),
    o('Layered protection and Diversification', 'Prevention and Detection', 'Confidentiality and Integrity', 'Sensitivity differentiation and Information hiding'),
    o('Sensitivity/privilege differentiation and Information hiding', 'Layered protection and Diversification', 'Prevention and Recovery', 'Economy of mechanism and Open design'),
    o('Security, Cost, Functionality, User expertise', 'Confidentiality, Integrity, Availability, Accountability', 'Prevention, Detection, Recovery, Reaction', 'Assets, Vulnerabilities, Threats, Risk'),
    o('Hardware, OS kernel, Operating system, Services, Applications', 'Applications, Services, OS, Kernel, Hardware', 'Kernel, Hardware, Services, OS, Applications', 'Hardware, Firmware, Network, OS, Users'),
    o('Quantitative risk analysis', 'Qualitative risk analysis', 'Defence-in-Depth', 'Asset valuation'),
    o('Defence-in-Depth (Layered protection)', 'Compartmentalisation', 'Fail-safe defaults', 'Separation of privilege'),
  ],
  2: [
    o('Confidentiality, Integrity, Availability, Accountability, Privacy', 'Confidentiality, Integrity, Availability', 'Identification, Authentication, Authorisation, Accountability, Privacy', 'Security, Robustness, Capacity, Cost, Speed'),
    o('Security, Robustness, Capacity', 'Confidentiality, Integrity, Availability', 'Correctness, Impersonation prevention, Transferability protection', 'Identification, Authentication, Authorisation'),
    o('Correctness, Impersonation prevention, Protection against transferability', 'Confidentiality, Integrity, Availability', 'Something you know, have, are', 'Identification, Authentication, Authorisation'),
    o('Something you are (behavioral characteristics)', 'Something you know', 'Something you have', 'Something you trust'),
    o('Subject s can read object o iff L(o) <= L(s) and s may read o', 'Subject s can read object o iff L(s) <= L(o)', 'Subject s can write object o iff L(o) <= L(s)', 'Subject s can read object o iff levels are equal'),
    o('A subject can read an object only if I(S) <= I(O)', 'A subject can read an object only if I(S) >= I(O)', 'A subject can write an object only if I(S) >= I(O)', 'A subject can invoke another only if I(S1) >= I(S2)'),
    o('Poor overview of access rights per object and difficult revocation', 'It cannot authenticate users', 'It stores passwords in plaintext', 'It only supports one object'),
    o('In DAC the resource owner controls access; in MAC rights are fixed centrally by an administrator', 'In DAC an administrator controls access; in MAC the owner does', 'Both are owner-controlled', 'DAC applies to files; MAC applies to users'),
    o('A hierarchy of access right levels; Ring 0 is the OS kernel', 'A list of user passwords; Ring 0 is the admin', 'A capability list; Ring 0 holds user processes', 'A conflict of interest class; Ring 0 is services'),
    o('Tamper-resistance, Complete mediation, Easiness of verification and testing', 'Confidentiality, Integrity, Availability', 'Identification, Authentication, Authorisation', 'Speed, Simplicity, Scalability'),
    o('The Chinese Wall model', 'The Bell-LaPadula model', 'The Biba model', 'Role Based Access Control'),
    o('A logical layer linking users and resources based on the need or circumstances of access', 'Access control carried out by the resource owner', 'Centralised access fixed by an administrator', 'Explicit revocation of access rights'),
    o('A subject can invoke another subject only if I(S1) >= I(S2)', 'A subject can read only if I(S) <= I(O)', 'A subject can write only if I(S) <= I(O)', 'A subject can read only if L(o) <= L(s)'),
    o('Identification, Authentication, Authorization, Accountability', 'Login, Request, Ticket, Accept', 'Confidentiality, Integrity, Availability, Privacy', 'Subject, Object, Reference Monitor, Group'),
    o('Hardware, OS kernel, Operating system, Services, Applications', 'Kernel, Hardware, Services, OS, Applications', 'Ring 0, 1, 2, 3, 4', 'Identification, Authentication, Authorization, Accountability, Audit'),
    o('Writes up', 'Writes down', 'Both writes up and down', 'Neither writes up nor down'),
    o('Step 6: Send TGS', 'Step 4: Send TGT', 'Step 8: Send Service Ticket', 'Step 1: Login'),
    o('Explicit revocation of access rights', 'A mapping of users to access rights', 'A collection of related subjects', 'A hierarchy of protection rings'),
    o('The Simple Security Property (ss-Property), informally "no reads up"', 'The *-Property, informally "no writes down"', 'The Biba simple integrity rule', 'The Chinese Wall *-property'),
    o('Reading Pizza Hut is blocked by the simple rule; writing to Ford is blocked by the *-property', 'Only the Pizza Hut read is blocked', 'Only the Ford write is blocked', 'Neither action is blocked'),
  ],
  3: [
    o('N x (N - 1) / 2', 'N x N', '2^N', 'N - 1'),
    o('Method (Transposition/Substitution), Key (Asymmetric/Symmetric), Processing (Stream/Block)', 'Confusion, Diffusion, Avalanche', 'Hash, Salt, Key', 'DES, AES, RSA'),
    o('XOR (Exclusive OR)', 'AND', 'Modular addition', 'Bit rotation'),
    o('6-bit input and 4-bit output', '4-bit input and 6-bit output', '8-bit input and 8-bit output', '32-bit input and 48-bit output'),
    o('C = E_k3(D_k2(E_k1(P)))', 'C = E_k1(E_k2(E_k3(P)))', 'C = D_k1(E_k2(D_k3(P)))', 'C = E_k1(D_k2(P))'),
    o('The One Time Pad', '3DES', 'Rijndael (AES)', 'The Feistel cipher'),
    o('No; it uses a state matrix with non-linear, mixing, and key addition layers', 'Yes; it is a Feistel network', 'Yes; like DES it splits the block in halves', 'No; it uses only transposition'),
    o('For a given D it is infeasible to find M such that D = h(M)', 'It is infeasible to find any two messages with the same hash', 'It is infeasible to find M\' != M with the same hash', 'It is infeasible to compute the hash'),
    o('2^(n/2) operations', '2^n operations', 'n^2 operations', 'n x (n-1)/2 operations'),
    o('Certification Authority, Registration Authority, Users/Subscriber, Repository/Archive', 'Sender, Receiver, Key, Cipher', 'CA, Firewall, VPN, IDS', 'Hash, Salt, Certificate, Key'),
    o('Registration Authority (RA)', 'Certification Authority (CA)', 'Repository/Archive', 'The Subscriber'),
    o('Data Integrity and Non-repudiation', 'Confidentiality and Integrity', 'Confidentiality and Availability', 'Authentication and Confidentiality'),
    o('Active attacks alter resources/operation; Passive attacks only learn information without affecting resources', 'Active attacks only eavesdrop; Passive attacks modify data', 'Active attacks are undetectable; Passive attacks are preventable', 'They are the same'),
    o('Masquerade and replay', 'Eavesdropping and traffic analysis', 'Confusion and diffusion', 'Snooping and sniffing'),
    o('An Adjudicated Protocol', 'An Arbitrated Protocol', 'A Zero Knowledge Protocol', 'A Feistel Protocol'),
    o('Certificate Revocation Lists (CRLs)', 'The X.509 certificate', 'The Registration Authority list', 'The session key archive'),
    o('An entity name to its public key', 'A password to its hash', 'A symmetric key to a session', 'A private key to a certificate'),
    o('A diffusion property where a 1-bit change cascades into large ciphertext differences', 'Substitution that obscures the key relationship', 'Shrinking of ciphertext per round', 'The reuse of a one time pad'),
    o("Bob's public key to encrypt; Bob's private key to decrypt", "Alice's private key to encrypt; Alice's public key to decrypt", "A shared symmetric key for both", "Bob's private key to encrypt; Bob's public key to decrypt"),
    o("Decrypt the attached hash with Sue's public key; valid if it matches his computed hash", "Encrypt the contract with Sue's public key", "Hash Sue's public key and compare", "Decrypt with his own private key"),
  ],
  4: [
    o('No; UNIX explicitly does not have a security architecture', 'Yes; UNIX has a unified, centrally managed architecture', 'Yes; via Active Directory', 'Only on the kernel level'),
    o('The Security Reference Monitor', 'The Local Security Authority (LSA)', 'The Security Accounts Manager (SAM)', 'Active Directory'),
    o('The Security Accounts Manager (SAM)', 'The Security Reference Monitor', 'The Local Security Authority (LSA)', 'The Access Token'),
    o('Security Identifier', 'System Identity Descriptor', 'Secure Inode Directory', 'Session ID'),
    o('A UID is a fixed 16-bit number; a SID is a variable-length machine-generated code', 'A UID is variable length; a SID is fixed 16-bit', 'Both are fixed 32-bit numbers', 'A UID is a string; a SID is an integer'),
    o('Owner SID, Primary Group SID, DACL, SACL', 'LSA, SAM, SRM, UAC', 'UID, GID, inode, umask', 'TGT, TGS, AS, SID'),
    o('A Privilege', 'An Access Right', 'A DACL entry', 'A capability'),
    o('rw-r--r-- (owner read/write, group read, others read)', 'rwxr--r--', 'rw-rw-r--', 'r--r--r--'),
    o('Only the file owner (or root) can remove files in that directory', 'It makes the directory read-only', 'It runs files under the owner privilege', 'It hides the directory contents'),
    o('-r (read-only), -o nosuid, -o noexec, -o nodev', '-w, -x, -r, -o exec', '-o suid, -o dev, -o exec', '-r, -o setuid, -o sticky'),
    o('fork creates an identical child; vfork is the same but shares memory', 'fork shares memory; vfork creates a copy', 'fork replaces the process image; vfork spawns a child', 'They are identical'),
    o('Real UID is inherited from the parent; effective UID may come from the parent or the executed file owner', 'Real UID comes from the file owner; effective from the parent', 'They are always identical', 'Effective UID is always 0'),
    o('DES', 'MD5', 'SHA-1', 'Blowfish'),
    o('/var/log/kern.log', '/etc/passwd', '/var/log/auth.log', '/etc/shadow'),
    o('Modularity, portability, efficiency', 'Confidentiality, integrity, availability', 'Security, speed, simplicity', 'Authentication, authorisation, auditing'),
    o('Any three of: ACLs, Data labeling, Mandatory access control, Capabilities, Standardized auditing', 'Firewalls, IDS, VPNs', 'SUID, sticky bit, umask', 'SID, DACL, SACL'),
    o('Credential Guard', 'Device Guard', 'Windows Hello', 'Trusted Boot'),
    o('WRITE_DAC', 'WRITE_OWNER', 'GENERIC_READ', 'SeShutdownPrivilege'),
    o('644', '633', '666', '755'),
    o('750: owner rwx, group r-x, others none', '755: owner rwx, group r-x, others r-x', '640: owner rw-, group r--, others none', '777: full access for everyone'),
  ],
  5: [
    o("Program code executed without a user's consent that carries out harmful functionality", 'Any program that accesses the network', 'Software with a graphical interface', 'A legally licensed application'),
    o('A Virus needs a host file to propagate; a Worm spreads independently over a network', 'A Virus spreads independently; a Worm needs a host file', 'They are the same thing', 'A Virus targets hardware; a Worm targets software'),
    o('Function arguments, Return address, Frame pointer, Local variables', 'Heap, Stack, Registers, Cache', 'Owner, Group, Others, Sticky', 'DEP, ASLR, Canary, Salt'),
    o('Data Execution Protection, Address Space Layout Randomisation, Canaries', 'Firewalls, VPNs, IDS', 'Encryption, Hashing, Salting', 'DEP, SQL escaping, input filtering'),
    o('An existing authenticated session, by tricking the browser into sending a forged request', 'A buffer overflow in the login form', 'An unfiltered script reflected to the browser', 'A weak password hash'),
    o('GET puts parameters in the URI (no side-effects); POST puts them in the body (potential side-effects)', 'GET sends data in the body; POST in the URI', 'GET has side-effects; POST is safe', 'They are identical'),
    o('Validate/Sanitise Input, Parameterised Input, SQL Escape', 'DEP, ASLR, Canaries', 'Encryption, Hashing, Salting', 'Firewall, IDS, VPN'),
    o('Encryption makes a document unreadable without a key; watermarking leaves it intact and recognisable', 'Both make the document unreadable', 'Watermarking needs a key; encryption does not', 'Encryption hides a marker inside the file'),
    o('Unobtrusive, Readily Detectable, Unambiguous, Innumerable, Robust', 'Encrypted, Compressed, Signed, Hashed, Salted', 'Fast, Cheap, Small, Visible, Editable', 'Spatial, Frequency, Text, Audio, Video'),
    o('Text Line Coding, Word-shift Coding, Character/Typeface Encoding', 'LSB, MSB, Frequency shifting', 'Jitter, StirMark, Cropping', 'DEP, ASLR, Canaries'),
    o('Spatial changes pixel LSBs; Frequency Domain applies the watermark in low-frequency redundant areas', 'Spatial uses frequency transforms; Frequency Domain edits pixels', 'Both edit the same pixel bits', 'Spatial is robust; Frequency is fragile'),
    o('It makes the WHERE clause always true (1=1), granting access even with an empty password', 'It deletes the password table', 'It encrypts the query', 'It overflows the login buffer'),
    o('Any three of: Ownership Assertion, Fingerprinting, Authentication, Content labeling, Usage control', 'DEP, ASLR, Canaries', 'GET, POST, PUT', 'Virus, Worm, Trojan'),
    o('The return address', 'The frame pointer', 'The heap', 'The function arguments'),
    o('Preparation, Identification, Containment, Eradication, Recovery, Lessons Learned', 'Detect, Analyse, Contain, Erase, Restore, Review', 'Prevention, Detection, Recovery', 'Scan, Patch, Monitor, Report, Audit, Close'),
    o('The printing/scanning process', 'A network flooding attack', 'Lossy compression', 'An LSB plane removal'),
    o('It precedes the return value with a special value and checks if it changed after the call', 'It encrypts the return address', 'It randomises the stack layout', 'It marks the stack non-executable'),
    o('It splits the signal into chunks and duplicates or deletes them at random, tweaking lower-order bits', 'It applies geometric stretching and rotation', 'It floods the watermark detector', 'It encrypts the watermark bits'),
    o('Cross-Site Scripting (XSS)', 'Cross-Site Request Forging (XSRF)', 'SQL Injection', 'Buffer Overflow'),
    o('Buffer Overflow; defended by Address Space Layout Randomisation (ASLR)', 'SQL Injection; defended by parameterised input', 'XSS; defended by input filtering', 'CSRF; defended by anti-forgery tokens'),
  ],
};

module.exports = { standard, extended };
